import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Login.module.css";
import Navbar from 'react-bootstrap/Navbar';
import Container from 'react-bootstrap/Container';
import { useRef, useEffect } from 'react';
import { useCookies } from 'react-cookie';
import { useRouter } from 'next/router';

import axios from 'axios';
import { backend_link } from "@/utils/backend";

const inter = Inter({ subsets: ["latin"] });

export default function Login() {
    const username = useRef();
    const password = useRef();
    const [cookies, setCookie] = useCookies(['username']);
    const router = useRouter();

    useEffect(() => {
        if (cookies.username) {
            router.push("/");
        }
    });

    let formdata = new FormData();

    const submitLogin = (e) => {
        e.preventDefault();
        formdata.append('username', username.current.value);
        formdata.append('password', password.current.value);

        axios.postForm(backend_link + '/auth/login', {
            username: username.current.value,
            password: password.current.value
            }).then((res) => {
                setCookie('username', res.data.username);
                router.push("/");
            }).catch((err) => {
                console.log(err);
            });
    }

    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={`${inter.className}`}>
        <Navbar className="bg-body-tertiary" bg="dark" data-bs-theme="dark">
        <Container>
          <Navbar.Brand href="#home">Peer to Peer Energy Trading System</Navbar.Brand>
        </Container>
      </Navbar>
            <h1 id={styles.heading}>Login</h1>
            <form id={styles.form} onSubmit={submitLogin}>
            <div id={styles.tb}>
                <input type="text" id={styles.username} name="username" placeholder="username" ref={username} /><br />
                <input type="password" id={styles.password} name="password" placeholder="password" ref={password} /><br />
            </div>
            <button type="submit" id={styles.submitbtn} className="btn btn-primary">Log in</button>
            </form>
        </main>
      </>
    );
  }
  