import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Login.module.css";
import Navbar from 'react-bootstrap/Navbar';
import Container from 'react-bootstrap/Container';
import { useRef } from 'react';
import { useRouter } from 'next/router';

import axios from 'axios';
import { backend_link } from "@/utils/backend";

const inter = Inter({ subsets: ["latin"] });

export default function Signup() {
    const username = useRef();
    const email = useRef();
    const password = useRef();
    const router = useRouter();

    const submit = (e) => {
        e.preventDefault();

        axios.post(backend_link + '/auth/signup', {
            username: username.current.value,
            email: email.current.value,
            password: password.current.value
            }).then((res) => {
                alert("Account Created");
                router.push("/login");
            }).catch((err) => {
                alert("Error creating account");
        })
    }

    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={`${styles.main} ${inter.className}`}>
        <Navbar className="bg-body-tertiary" bg="dark" data-bs-theme="dark">
        <Container>
          <Navbar.Brand href="#home">Peer to Peer Energy Trading System</Navbar.Brand>
        </Container>
      </Navbar>
            <h1 id={styles.heading}>Sign Up</h1>
            <form id={styles.form} onSubmit={submit}>
            <div id={styles.tb}>
                <input type="text" id={styles.username} name="username" placeholder="username" ref={username} /><br />
                <input type="email" id={styles.email} name="email" placeholder="email" ref={email} /><br />
                <input type="password" id={styles.password} name="password" placeholder="password" ref={password} /><br />
            </div>
            <button type="submit" id={styles.submitbtn} className="btn btn-primary">Sign up</button>
            </form>
          
        </main>
      </>
    );
  }
  